server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_swp
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: hieuhoangminh841@gmail.com
    password: rqkw nvyb gwfa zqwf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: admin
      password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
