server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swp
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: hieuhoangminh841@gmail.com
    password: rqkw nvyb gwfa zqwf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    user:
      name: admin
      password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: DEBUG
vnpay:
  tmnCode: K3HKZRGO
  hashSecret: XLOMXOCMCMDTWKIT4ZKZ5CYMU1VLWBD5
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/payment/vnpay-return
  ipnUrl: http://localhost:8080/api/payment/vnpay-ipn